server:
  port: 8004

spring:
  application:
    name: cloud-provider-paymentCsl8004
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
#        hostname: 127.0.0.1
        service-name: ${spring.application.name}
#        health-check-path: /health
#        health-check-interval: 10s
